#pragma once
#include "Core/Inc/Core.h"
//#include "Vector2.h"
//#include "Vector3.h"
//#include "Vector4.h"
//#include "Matrix4.h"
//#include "Quaternion.h"
//#include "Constants.h"
#include <cmath>
#include <numeric>
#include <random>